server:
  port: 6999
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jpa_test
    username: root
    password: 19980617pyr
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    properties:
      hibernate:
        #        generate_statistics: true
        order_inserts: true
        order_updates: true
        jdbc:
          batch_size: 1000
          batch_versioned_data: true